# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development

In [3]:
#pip install nbconvert pip install pyppeteer

In [4]:
#--allow-chromium-download

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [9]:
arr1=np.repeat([1],10)
print(arr1)

arr2 = np.arange(0, 21, 1, dtype="int") #Use a range array from 0 to 21, with an increment of 1, set datatype to integer.
print(arr2)

arr3 = np.ones((1, 5, 5))
print(arr3)

[1 1 1 1 1 1 1 1 1 1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [11]:
matrix=np.random.randn(3,3,3)
print(matrix)

reshaped_matrix=matrix.reshape(27)
print(reshaped_matrix)

[[[ 0.13908726  0.95731085 -0.5550318 ]
  [-0.20729202  0.15393781 -0.97584091]
  [-0.74323105  1.65931456 -1.18845112]]

 [[-2.3407766  -1.26262363 -0.14891267]
  [-1.95312429 -0.31974306  0.58621324]
  [ 0.87073415  0.77879813 -1.77519296]]

 [[ 0.38542459  1.50794241  0.12231394]
  [ 1.63634609 -0.36677491 -0.20189217]
  [ 1.66713667  0.9101554  -1.84438364]]]
[ 0.13908726  0.95731085 -0.5550318  -0.20729202  0.15393781 -0.97584091
 -0.74323105  1.65931456 -1.18845112 -2.3407766  -1.26262363 -0.14891267
 -1.95312429 -0.31974306  0.58621324  0.87073415  0.77879813 -1.77519296
  0.38542459  1.50794241  0.12231394  1.63634609 -0.36677491 -0.20189217
  1.66713667  0.9101554  -1.84438364]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [12]:
arr3=np.linspace(1,10,20)
print(arr3)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [16]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
20

In [18]:
print(a[3,4])

20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [30]:
print(a[1:5, 3:5])


[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([ 6,  7,  8,  9, 10])
```

In [32]:
print(a[1,0:5])

[ 6  7  8  9 10]


## 2.5 

Calculate the sum of all the numbers in `a`.

In [33]:
sum_of_a = np.sum(a)
print(sum_of_a)

325


## 2.6 

Calculate the sum of each row in `a`.

In [34]:
sum_of_rows_in_a = [sum(row) for row in a]
print(sum_of_rows_in_a)

[15, 40, 65, 90, 115]


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [37]:
average_a=a.mean()
values=a[a>average_a]
print(values)

[14 15 16 17 18 19 20 21 22 23 24 25]


# Practicing Pandas

## 2.8

In this we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [38]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [49]:
url="https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv"
df=pd.read_csv(url)
print(df.head())

     country food_category  consumption  co2_emmission
0  Argentina          Pork        10.51          37.20
1  Argentina       Poultry        38.66          41.53
2  Argentina          Beef        55.48        1712.00
3  Argentina   Lamb & Goat         1.56          54.63
4  Argentina          Fish         4.36           6.96


## 2.10 

How many rows and columns are there in the dataframe?

In [51]:
rows, columns=df.shape
print("# of rows:",rows)
print("# of columns:",columns)

# of rows: 1430
# of columns: 4


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [57]:
co2_avg=df['co2_emmission'].mean()
print("Mean CO2 Emission of whole dataset:",co2_avg)

Mean CO2 Emission of whole dataset: 74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [70]:
max_co2_emmission = df['co2_emmission'].max()
query=df[df['co2_emmission']==max_co2_emmission]
country1= query['country'].values[0]
food_type= query['food_category'].values[0]
print(food_type,"in",country1, "has maximum CO2 emmissions of", max_co2_emmission)

Beef in Argentina has maximum CO2 emmissions of 1712.0


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [79]:
k_emmissions=df[df['co2_emmission']>1000]
num_countries_with_emmissions=k_emmissions['country'].nunique()
countries_with_emmissions=k_emmissions['country'].unique()
print("There are ",num_countries_with_emmissions, "countries that produce more than 1000kg CO2/person/year for at least one food type.")
print(countries_with_emissions)

There are  5 countries that produce more than 1000kg CO2/person/year for at least one food type.
['Argentina' 'Australia' 'USA' 'Brazil' 'Bermuda']


## 2.14

Which country consumes the least amount of beef per person per year?


In [87]:
df_beef=df[df['food_category']=='Beef']
min_beef=df_beef['consumption'].idxmin()
country_min_beef=df_beef.loc[min_beef, 'country']
min_consumption=df_beef.loc[min_beef, 'consumption']
print("The country that consumes the least amount of beef per year is", country_min_beef, ", consuming", min_consumption, "of beef per person per year.")

The country that consumes the least amount of beef per year is Liberia , consuming 0.7799999999999999 of beef per person per year.


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [89]:
meat_products = ["Pork","Poultry","Fish","Lamb & Goat", "Beef"]
df_meat=df[df['food_category'].isin(meat_products)]
total_emmissions_meat=df_meat['co2_emmission'].sum()
print("The total emissions of all the meat products in the dataset combined is", total_emmissions_meat)

The total emissions of all the meat products in the dataset combined is 74441.13


# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [90]:
meat_products = ["Pork","Poultry","Fish","Lamb & Goat", "Beef"]
df_notmeat=df[~df['food_category'].isin(meat_products)]
total_emmissions_notmeat=df_notmeat['co2_emmission'].sum()
print("The total emissions of all the non-meat products in the dataset combined is", total_emmissions_notmeat)

The total emissions of all the non-meat products in the dataset combined is 31927.98


## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.